server:
  port: 8765
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  #cloud:
  #  config:
  #    username: siggConfig
  #    password: s1ggP4ssw0rd
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#jwt:
#  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY