server:
  port: 8100
spring:
  #config:
        #import: optional:configserver:http://localhost:8888
  application:
    name: login-service
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: http
      kv-version: 2
      authentication: TOKEN
      #token: s.msk4vX3ppa1tOSwbEGpxUCs4
      #uri: http://127.0.0.1:8200
  datasource:
    username: root
    password: s1gg#Us3r#P4ss
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/sigg?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/